language: objective-c
osx_image: xcode9.4
script:
    - xcodebuild clean test -project ios-mvp-pattern-example.xcodeproj -scheme ios-mvp-pattern-example CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet