language: objective-c
osx_image: xcode9.4
script:
    - xcodebuild -workspace ios-mvp-pattern-example.xcworkspace -scheme ios-mvp-pattern-example -sdk iphonesimulator -destination platform="iOS Simulator,name=iPhone 8,OS=11.4" test